// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB71wcurEoIvmz0sHypSXb_ZIx2jg4PHVM',
    appId: '1:460968991742:web:a408eab2993a347d4a7eaf',
    messagingSenderId: '460968991742',
    projectId: 'flutter-ui-testi',
    authDomain: 'flutter-ui-testi.firebaseapp.com',
    storageBucket: 'flutter-ui-testi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWm5hJAKm3k-ubp4Lnj7MFAA9CH_GZbE',
    appId: '1:460968991742:android:66dde091a126cac34a7eaf',
    messagingSenderId: '460968991742',
    projectId: 'flutter-ui-testi',
    storageBucket: 'flutter-ui-testi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtGPkpP8Prl1FYf-Ot1-WjIliAR9ftkKc',
    appId: '1:460968991742:ios:ade8ee765aa70eea4a7eaf',
    messagingSenderId: '460968991742',
    projectId: 'flutter-ui-testi',
    storageBucket: 'flutter-ui-testi.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUitreeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtGPkpP8Prl1FYf-Ot1-WjIliAR9ftkKc',
    appId: '1:460968991742:ios:ade8ee765aa70eea4a7eaf',
    messagingSenderId: '460968991742',
    projectId: 'flutter-ui-testi',
    storageBucket: 'flutter-ui-testi.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUitreeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB71wcurEoIvmz0sHypSXb_ZIx2jg4PHVM',
    appId: '1:460968991742:web:815a18fc3282e82d4a7eaf',
    messagingSenderId: '460968991742',
    projectId: 'flutter-ui-testi',
    authDomain: 'flutter-ui-testi.firebaseapp.com',
    storageBucket: 'flutter-ui-testi.firebasestorage.app',
  );

}